### ISSUE TITLE
differences between `mvn clean install` and `mvnd clean install`

### ISSUE THREAD

**Issue by maxandersen** [mvndaemon/mvnd#25] opened 2020-05-05 20:50 UTC
I used ` mvnd clean install -DskipTests -DskipITs -Dquarkus.build.skip -DskipDocs -Denforcer.skip` twice in quarkus root now and both times I don't seem to end up with jars/classes in the ~/.m2 repo that corresponds to what `mvn clean install` brings.

The way I realize there is an issue is that breakpoints were not being hit and main diff was that newly updated code from a pull request did not seem to be included in the build.

My best guess is that mvnd might do some time comparison and the PR's files are from before last build  thus they  are not included in the build or something similar ?

I wish I could be more precise :)

**Comment by ppalaga** [comment] 2020-05-06 08:30
I have found another issue when trying to dig into this one: https://github.com/gnodet/mvnd/issues/25

**Comment by ppalaga** [comment] 2020-05-06 14:48
In case this is really caused by malfunctioning classloader cache, as suggested by @gnodet in #26 then the issue can be workarounded by killing the daemon `mvnd --stop` each time you change code loaded by some of the quarkus plugins.

**Comment by ppalaga** [comment] 2020-05-11 15:49
It seems like mvnd is not picking the changes in camel-quarkus-bom. Let me properly record the steps to reproduce next time I see it.

**Comment by ppalaga** [comment] 2020-06-28 17:29
mvnd is indeed malfunctioning when there is a Mojo in the source tree and it is used in another module. https://github.com/mvndaemon/mvnd/issues/33  links a reproducer. We have such a situation in Quarkus, so this may well be a root cause of what @maxandersen sees.

I still have to check if changes in BOM are picked.

**Comment by ppalaga** [comment] 2020-07-31 13:11
Closing as the plugin classloader cache invalidation issue should be solved as of mvnd 0.0.1 (see https://github.com/mvndaemon/mvnd/releases/tag/0.0.1 ) and I have not seen any issue related to changes in BOM for some time now.

@maxandersen thanks for the report and looking forward for new reports if you give mvnd the second chance!

**Closed by ppalaga** 2020-07-31 13:11 UTC
