### ISSUE TITLE
NullPointerException in integration tests with maven-surefire-plugin 3.0.0-M5

### ISSUE THREAD

**Issue by ppalaga** [mvndaemon/mvnd#103] opened 2020-10-18 07:42 UTC
Happens intermittently on all OSes. 

Steps to reproduce:

* Revert ec6280f4f7a9bf6f9cae87a1b3ff0e29b651e736
* Run the tests in JVM mode with `-Dmrm=false` until the exception occurs

**Comment by famod** [comment] 2020-10-20 21:43
What does the stacktrace look like?

**Comment by ppalaga** [comment] 2020-10-20 22:13
> What does the stacktrace look like?

I do not know anymore, sorry. I'd have to revert ec6280f and run the build myself.

**Comment by famod** [comment] 2020-10-22 12:07
Just tried it:
```
",  "[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ multi-module-hi ---
",  "[INFO] Surefire report directory: C:\_dev\git\mvnd\integration-tests\target\mvnd-tests\MultiModuleTest\project\hi\target\surefire-reports
    "[WARN] Failed to write tracking file C:\_dev\git\mvnd\integration-tests\target\mvnd-tests\MultiModuleTest\local-maven-repo\org\apiguardian\apiguardian-api\1.0.0\apiguardian-api-1.0.0.pom.lastUpdated
java.io.FileNotFoundException: C:\_dev\git\mvnd\integration-tests\target\mvnd-tests\MultiModuleTest\local-maven-repo\org\apiguardian\apiguardian-api\1.0.0\apiguardian-api-1.0.0.pom.lastUpdated (Zugriff verweigert)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
        at io.takari.aether.localrepo.TrackingFileManager.update(TrackingFileManager.java:78)
        at io.takari.aether.localrepo.TakariUpdateCheckManager.write(TakariUpdateCheckManager.java:451)
        at io.takari.aether.localrepo.TakariUpdateCheckManager.touchArtifact(TakariUpdateCheckManager.java:394)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.evaluateDownloads(DefaultArtifactResolver.java:619)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:510)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:401)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:262)
        at org.apache.maven.project.CachingProjectBuilder.build(CachingProjectBuilder.java:283)
        at org.apache.maven.project.CachingProjectBuilder.build(CachingProjectBuilder.java:266)
        at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedProject(MavenMetadataSource.java:591)
        at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:211)
        at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:551)
        at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:605)
        at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.collect(DefaultLegacyArtifactCollector.java:148)
        at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:504)
        at org.apache.maven.repository.legacy.LegacyRepositorySystem.resolve(LegacyRepositorySystem.java:367)
        at org.apache.maven.plugin.surefire.SurefireDependencyResolver.resolveArtifact(SurefireDependencyResolver.java:202)
        at org.apache.maven.plugin.surefire.SurefireDependencyResolver.resolvePluginArtifact(SurefireDependencyResolver.java:183)
        at org.apache.maven.plugin.surefire.SurefireDependencyResolver.resolvePluginArtifact(SurefireDependencyResolver.java:173)
        at org.apache.maven.plugin.surefire.SurefireDependencyResolver.getProviderClasspath(SurefireDependencyResolver.java:212)
        at org.apache.maven.plugin.surefire.SurefireDependencyResolver.getProviderClasspathAsMap(SurefireDependencyResolver.java:230)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo$JUnitPlatformProviderInfo.getProviderClasspath(AbstractSurefireMojo.java:3215)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.newStartupConfigWithClasspath(AbstractSurefireMojo.java:1908)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.createStartupConfiguration(AbstractSurefireMojo.java:1894)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.createForkStarter(AbstractSurefireMojo.java:2374)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1310)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.jboss.fuse.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:174)
        at org.jboss.fuse.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:194)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
",      at java.base/java.lang.Thread.run(Thread.java:834)
```
```
    "[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project multi-module-hi: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test failed.: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project multi-module-hi: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.jboss.fuse.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:174)
        at org.jboss.fuse.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:194)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        ... 10 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo$ClasspathCache.setCachedClasspath(AbstractSurefireMojo.java:4121)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo$ClasspathCache.access$200(AbstractSurefireMojo.java:4102)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.newStartupConfigWithClasspath(AbstractSurefireMojo.java:1913)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.createStartupConfiguration(AbstractSurefireMojo.java:1894)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.createForkStarter(AbstractSurefireMojo.java:2374)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1310)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
",      ... 11 common frames omitted
```

**Comment by famod** [comment] 2020-10-22 12:10
That leaves us with https://issues.apache.org/jira/browse/SUREFIRE-1837 which contains a workaround in the first comment.

**Comment by ppalaga** [comment] 2020-10-22 12:54
Thanks for the investigation. I was suspecting this is a Surefire issue rather than ours. Let's keep this open until there is a Surefire 3.0.x version that works for us.

**Comment by Tibor17** [comment] 2020-10-22 14:27
The problem is at the [Line 4153](https://github.com/apache/maven-surefire/blob/master/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java#L4153) of current revision.
The lines have moved a little bit after the release 3.0.0-M5.

My question is why the dependency has NULL artifact file - JAR.
Should we surround the statemen by a null check? Is it enough?

**Comment by ppalaga** [comment] 2020-10-22 15:52
> My question is why the dependency has NULL artifact file - JAR.

Because it happens intermittently and because our tests run on multiple cores by default, I guess that there is some race condition happening somewhere. We are maybe getting a mutable instance of `org.apache.maven.artifact.Artifact` that is resolved in one thread and used in another? Maybe there is a memory barrier missing somewhere.

> Should we surround the statement by a null check? Is it enough?

I do not think so, although I do not know all details. The files are supposed to be there for resolved artifacts, aren't they?

**Comment by Tibor17** [comment] 2020-10-22 16:06
@ppalaga This MOJO class (AbstractSurefireMojo) runs in one Thread.
The Maven itself may be unsafe due to race conditioning.

Let's confirm that we have multiple threads somewhere.
My question is, where are these Threads coming from?
Do you run Maven like this `mvn test -T 2C` ?

Is is permanently reproducible problem?
If it is not, then it looks like a race conditioning problem.

>> The files are supposed to be there for resolved artifacts, aren't they?
Yes, the files are supposed to be there. Although the plugin and Maven, both, can resolve the artifacts.
Maybe it's worth to reproduce the problem on my side. What are the instructions to reproduce it?

**Comment by ppalaga** [comment] 2020-10-22 16:32
> @ppalaga This MOJO class (AbstractSurefireMojo) runs in one Thread.
> The Maven itself may be unsafe due to race conditioning.
> 
> Let's confirm that we have multiple threads somewhere.
> My question is, where are these Threads coming from?
> Do you run Maven like this `mvn test -T 2C` ?

Yes, mvnd passes -Tn to Maven by default where n is number-of-cores minus one.

> Is is permanently reproducible problem?

No, it happens sometimes.
git@github.com:mgit@github.com:mvndaemon/mvnd.gitvndaemon/mvnd.git
> If it is not, then it looks like a race conditioning problem.
> 
> > The files are supposed to be there for resolved artifacts, aren't they?
> 
> Yes, the files are supposed to be there. Although the plugin and Maven, both, can resolve the artifacts.
> Maybe it's worth to reproduce the problem on my side. What are the instructions to reproduce it?

Thanks a lot, here are the instructions:

```
git clone git@github.com:mvndaemon/mvnd.git
cd mvnd
git revert ec6280f
mvn install -DskipTests
cd integration-tests

# repeat untill you see the bug
mvn test -Dmrm=false
```

**Comment by Tibor17** [comment] 2020-10-22 20:03
@ppalaga 
I saw that you refered to the nested ITs and their logs.
I could not reproduce this issue. But I think i know where the problem might be.
Try to ask the Maven developers in the mailing list and refer to the Maven Resolver.
The Maven version has to be written in the email and the JDK as well.

The resolver uses multiple threads. Try to refer to the abilities of resolver to use multiple threads, conditions to use multiple threads and logging the resolver.
The developers may ask you about the CLI of each IT. This needs to be explicitely specified in the email without letting them to dig into your project too much.

**Comment by AntoineRondelet** [comment] 2021-01-15 16:21
Hi everyone,

I think I have the same issue while using the `maven-surefire-plugin 3.0.0-M5` plugin with:
```console
❯❯❯ mvn --version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.9.1, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
```

In fact, as explained in https://github.com/clearmatics/dizk/issues/1 (description pasted below):
> For now, the `DistributedzkSNARKTest` class runs 3 tests. One for a "fake" pairing group and one for BN254a, BN254b.
After bumping all plugins/dependency/JDK/Compiler versions the tests fail because of this test class (`DistributedzkSNARKTest`).
> In fact, the execution of `DistributedBN254bProofSystemTest` throws a `NullPtr` exception, which after a close look to the code doesn't immediately make sense. After commenting the 2 first test cases (namely `DistributedBN254aProofSystemTest` and `DistributedFakeProofSystemTest`) the test pass nicely and the NullPtr isn't thrown. This is confirmed by the fact that when executing each function annotated with `@Test` in the class independently in an IDE, all functions pass. As such, it seems that the issue come from `surefire`. That being said, I can't pinpoint where things go wrong, it seems that the `this.G1Parameters` (where `this` is the `g1Factory` for the BN254b pairing group) become `null` as some point in the execution of the test when all tests of the `DistributedzkSNARKTest` class are executed. I can't think about any place where this object is modified...
> This needs further investigation - and will probably translate into opening a ticket to surefire to see if this can come from there.

I ported a fairly old project to java 11 and used a more recent version for mvn as well as bumped the version of JUnit from 4.11 to 5.7 and used surefire. However, some tests are now failing due to a "NullPtr" exception.
As per the quoted message above, I suspect there is a race condition somewhere as I inspected our code and could't make any sense of this exception. Likewise, as mentioned above, running all tests individually works just fine. Troubles appear when I want to run all my tests with `mvn clean test`.
I used `<reuseForks>false</reuseForks>` and `<forkCount>1</forkCount>` (see [pom.xml](https://github.com/clearmatics/dizk/blob/master/pom.xml#L76-L106)) to try and kill concurency and hope to get all my tests to pass but unfortunately, this still faills with the same exception.

(I saw this ticket https://issues.apache.org/jira/browse/SUREFIRE-1837 but couldn't get the recommended workaround to work in my case)

## Reproduction steps

```console
git clone -b nullptr-test git@github.com:clearmatics/dizk.git
cd dizk
git submodule init && git submodule update
mvn -Dtest=DistributedzkSNARKTest test
# The NullPointer Exception should be raised by the last command (executing both tests separately - by commenting the other in the source, shows that both tests pass - the exception is not raised in this case)
```

Would anyone of you have any recommendations as to how to resolve this on my end? Do I do something wrong?

Thanks in advance

**Comment by ppalaga** [comment] 2021-01-19 16:27
I unfortunately do not have time to dig into surefire 3 issues. Sticking to surefire 2.22 worked well for me on all occasions so far.

**Comment by Tibor17** [comment] 2021-01-19 20:12
Hi Peter,

I remember this issue with NPE in Artifact. It is quite an old one.
I answered the issue in the comment [1] but I am more convinced that the
Resolver tool, which is another library, is concurrent itself.
So my advice would be to disable concurrent Threads in the Resolver and
check it out.
We had some discussion about the concurrency in the Maven team and the code
of Resolver a few years ago.
Please try to disable the concurrency of Resolver and try to run the build
several times again, and let us know your results.

[1]: https://github.com/mvndaemon/mvnd/issues/103#issuecomment-71453283
[2]: https://github.com/mvndaemon/mvnd/issues/103#issuecomment-714730092

Cheers
Tibor17

**Comment by Enigo** [comment] 2021-03-30 08:16
Hey @Tibor17,
are there any updates on the issue? 

> disable the concurrency

is not an optional solution as it slows down the build (in my case by around 30%)

Cheers

**Comment by Tibor17** [comment] 2021-03-30 21:51
@ppalaga 
@Enigo 
Let's continue in [JIRA](https://issues.apache.org/jira/browse/SUREFIRE-1837) but according to my analysis this issue is not related to Surefire project. The plugins depend on some external components which are separate libraries, and there I think we should discuss this issue witht the Maven development group on the mailing list. If the Surefire had a problem then it would not download any artifacts for you and it would be buggy all the time which is not this case. I think this has to to with locking problem of the artifact files on the file system and the expiration of the artifact update on your local repo. We in Maven had many issue like this, so we should redirect to another chat. Do you have account in our internal Apache Slack?

**Comment by famod** [comment] 2021-04-13 15:52
From https://issues.apache.org/jira/browse/SUREFIRE-1837?focusedCommentId=17320118&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17320118:
> try to use -Daether.metadataResolver.threads=1

**Comment by michael-o** [comment] 2021-04-22 17:12
This issue is invalid:
```
        at io.takari.aether.localrepo.TrackingFileManager.update(TrackingFileManager.java:78)
        at io.takari.aether.localrepo.TakariUpdateCheckManager.write(TakariUpdateCheckManager.java:451)
        at io.takari.aether.localrepo.TakariUpdateCheckManager.touchArtifact(TakariUpdateCheckManager.java:394)
```

I maintain Maven Resolver these days. Remove this third party component, it promises thread safety, but does not hold it. Look out for MRESOLVER-145.

**Comment by Tibor17** [comment] 2021-04-22 20:48
@michael-o 
Could it be part of `mrm-maven-plugin`?
I did not see Takari in this project.

**Comment by michael-o** [comment] 2021-04-22 21:02
Here it is https://github.com/takari/takari-local-repository

**Comment by gnodet** [comment] 2021-06-08 07:27
It seems those issues are fixed in surefire now.

**Closed by gnodet** 2021-06-08 07:27 UTC
