### ISSUE TITLE
The caches are not all cleaned when deleting the local repository

### ISSUE THREAD

**Issue by gnodet** [mvndaemon/mvnd#312] opened 2021-01-07 15:00 UTC
The following new test inside `SingleModuleNativeIT` test fails:

```
    @Test
    void buildDeleteRepoAndRebuild() throws IOException, InterruptedException {
        final Path localMavenRepo = parameters.mavenRepoLocal();
        TestUtils.deleteDir(localMavenRepo);

        final TestClientOutput o1 = new TestClientOutput();
        client.execute(o1, "clean", "install", "-e", "-B").assertSuccess();

        TestUtils.deleteDir(localMavenRepo);

        final TestClientOutput o2 = new TestClientOutput();
        client.execute(o2, "clean", "install", "-e", "-B").assertSuccess();
    }
```

**Comment by ppalaga** [comment] 2021-01-07 15:19
Sounds like a duplicate of https://github.com/mvndaemon/mvnd/issues/26 - let's close that one.

**Comment by gnodet** [comment] 2021-01-11 16:36
The commit https://github.com/mvndaemon/mvnd/commit/67d5b4b9c95e1f56d1287a2efccd33c67b091bdb might be a problem on OSX, as the WatchService on OSX uses polling, so file changes won't be detected if the repo is deleted and the launch started just after (the default polling interval is 10s on OSX).

However, even after fixing the problem, when the compilation failure happens, the repo has not been fully re-populated.  This means the resolution of artefacts is cached somehow.

**Comment by gnodet** [comment] 2021-01-11 19:21
It seems the problem is the `ProjectArtifactsCache` default implementation.

**Closed** 2021-01-13 15:01 UTC
