### ISSUE TITLE
Running maven daemon fails on windows

### ISSUE THREAD

**Issue by Dunemaster** [mvndaemon/mvnd#35] opened 2020-06-29 11:26 UTC
Running maven daemong fails on windows

Releases 0.0.0
Windows 10

```
E:\dev\g5rt\runtime>"E:\Program Files\mvnd\mvnd-windows-amd64"
Jun 29, 2020 12:57:30 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
[main] INFO org.jboss.fuse.mvnd.client.DaemonRegistry - Removing 0 daemon stop events from registry
[main] INFO org.jboss.fuse.mvnd.client.DaemonConnector - Starting a Maven Daemon (subsequent builds will be faster)
[main] INFO org.jboss.fuse.mvnd.client.DaemonConnector - Removing daemon from the registry due to communication failure. Daemon information: DaemonInfo{uid=192ee0bd-5fac-404a-9726-6e8b75cbac61javaHome=C:\Program Files\BellSoft\LibericaJDK-11, options=[], mavenHome=E:\mvnd, pid=27040, address=52076, idleTimeout=10800000, locale=ru-RU, state=Busy, lastIdle=1593424651736, lastBusy=1593424651736}
Exception in thread "main" org.jboss.fuse.mvnd.client.DaemonException$ConnectException: Could not connect to the Maven daemon.
Daemon uid: 192ee0bd-5fac-404a-9726-6e8b75cbac61
  log file: E:\mvnd\daemon\daemon-192ee0bd-5fac-404a-9726-6e8b75cbac61.log
----- Last  20 lines from daemon log file - E:\mvnd\daemon\daemon-192ee0bd-5fac-404a-9726-6e8b75cbac61.log -----
12:57:31.744 I Daemon started
12:57:31.747 D daemon is running. Sleeping until state changes.----- End of the daemon log -----

        at org.jboss.fuse.mvnd.client.DaemonConnector.connectToDaemonWithId(DaemonConnector.java:286)
        at org.jboss.fuse.mvnd.client.DaemonConnector.startDaemon(DaemonConnector.java:215)
        at org.jboss.fuse.mvnd.client.DaemonConnector.connect(DaemonConnector.java:97)
        at org.jboss.fuse.mvnd.client.DefaultClient.execute(DefaultClient.java:218)
        at org.jboss.fuse.mvnd.client.DefaultClient.main(DefaultClient.java:69)
Caused by: org.jboss.fuse.mvnd.client.DaemonException$ConnectException: Could not connect to server 0.0.0.0/0.0.0.0:52076.
        at org.jboss.fuse.mvnd.client.DaemonConnector.connect(DaemonConnector.java:341)
        at org.jboss.fuse.mvnd.client.DaemonConnector.connectToDaemon(DaemonConnector.java:295)
        at org.jboss.fuse.mvnd.client.DaemonConnector.connectToDaemonWithId(DaemonConnector.java:283)
        ... 4 more
Caused by: java.net.SocketException: Permission denied: no further information
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_net_SocketException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
        at com.oracle.svm.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java)
        at com.oracle.svm.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:801)
        at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:776)
        at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:120)
        at org.jboss.fuse.mvnd.client.DaemonConnector.connect(DaemonConnector.java:331)
        ... 6 more
```

**Comment by ppalaga** [comment] 2020-06-29 11:50
Have you been able to run `mvnd --install` before you got the above?

Could you please paste the content of `E:\mvnd\daemon\daemon-192ee0bd-5fac-404a-9726-6e8b75cbac61.log` ?

**Comment by ppalaga** [comment] 2020-06-29 11:51
Thanks for the report, BTW :)

**Comment by Dunemaster** [comment] 2020-06-29 12:09
>Have you been able to run mvnd --install before you got the above?
Yes, it ran ok.

**Comment by Dunemaster** [comment] 2020-06-29 12:09
[daemon-192ee0bd-5fac-404a-9726-6e8b75cbac61.log](https://github.com/mvndaemon/mvnd/files/4845366/daemon-192ee0bd-5fac-404a-9726-6e8b75cbac61.log)

**Comment by ppalaga** [comment] 2020-07-30 13:53
I was able to run `mvnd -v` (which connects to a daemon) successfully on windows. 

![image](https://user-images.githubusercontent.com/1826249/88931194-ce787580-d27c-11ea-9955-eb1971e26fd4.png)


Maybe you have too restrictive firewall settings? Windows defender asked me about the network access of java.exe when I have run it for the first time. I allowed both local and remote.

**Comment by ppalaga** [comment] 2020-07-30 13:54
Closing as "Can't reproduce"

**Closed by ppalaga** 2020-07-30 13:54 UTC
