### ISSUE TITLE
Better progress report

### ISSUE THREAD

**Issue by rmannibucau** [mvndaemon/mvnd#463] opened 2021-09-02 06:12 UTC
Hi

Right now progress report does not show the failure count - or I missed it.
Can be great (particularly on huge projects).
Not sure the failing modules should be listed at the top or not but at least  a red count of module build failure would help.

Romain

**Comment by gnodet** [comment] 2021-09-02 06:21
This looks like a duplicate of https://github.com/mvndaemon/mvnd/issues/361 which I've just committed.  You can give it a try, there's certainly room for improvements.

**Closed by gnodet** 2021-09-02 06:21 UTC

**Comment by rmannibucau** [comment] 2021-09-02 09:29
@gnodet with the snapshot I get:

````
Unable to create new sync context
java.lang.RuntimeException: TppWise Data: Unable to create new sync context
	at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:183)
	at org.mvndaemon.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:198)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.RuntimeException: Unable to create new sync context
	at org.mvndaemon.mvnd.sync.IpcClient.newContext(IpcClient.java:339)
	at org.mvndaemon.mvnd.sync.IpcSyncContext.<init>(IpcSyncContext.java:40)
	at org.mvndaemon.mvnd.sync.IpcSyncContextFactory.newInstance(IpcSyncContextFactory.java:53)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:255)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:107)
	at org.mvndaemon.mvnd.plugin.CliMavenPluginManager.lambda$getPluginDescriptor$0(CliMavenPluginManager.java:187)
	at org.mvndaemon.mvnd.cache.invalidating.InvalidatingPluginDescriptorCache.lambda$get$0(InvalidatingPluginDescriptorCache.java:100)
	at org.mvndaemon.mvnd.cache.impl.TimestampCacheFactory$TimestampCache.lambda$computeIfAbsent$2(TimestampCacheFactory.java:178)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at org.mvndaemon.mvnd.cache.impl.TimestampCacheFactory$TimestampCache.computeIfAbsent(TimestampCacheFactory.java:166)
	at org.mvndaemon.mvnd.cache.invalidating.InvalidatingPluginDescriptorCache.get(InvalidatingPluginDescriptorCache.java:98)
	at org.mvndaemon.mvnd.plugin.CliMavenPluginManager.getPluginDescriptor(CliMavenPluginManager.java:186)
	at org.mvndaemon.mvnd.plugin.CliMavenPluginManager.getMojoDescriptor(CliMavenPluginManager.java:272)
	at org.apache.maven.plugin.DefaultBuildPluginManager.getMojoDescriptor(DefaultBuildPluginManager.java:244)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.setupMojoExecution(DefaultLifecycleExecutionPlanCalculator.java:169)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.setupMojoExecutions(DefaultLifecycleExecutionPlanCalculator.java:154)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:130)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:144)
	at org.apache.maven.lifecycle.internal.builder.BuilderCommon.resolveBuildPlan(BuilderCommon.java:97)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:111)
	at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:178)
	... 6 common frames omitted
	Suppressed: java.lang.RuntimeException: Unable to create and connect to lock server
		at org.mvndaemon.mvnd.sync.IpcClient.createClient(IpcClient.java:238)
		at org.mvndaemon.mvnd.sync.IpcClient.ensureInitialized(IpcClient.java:89)
		at org.mvndaemon.mvnd.sync.IpcClient.send(IpcClient.java:290)
		at org.mvndaemon.mvnd.sync.IpcClient.newContext(IpcClient.java:342)
		... 30 common frames omitted
	Caused by: java.lang.UnsupportedOperationException: Unix sockets are supported only on JDK >= 16
		at org.mvndaemon.mvnd.common.SocketHelper.openUnixServerSocket(SocketHelper.java:30)
		at org.mvndaemon.mvnd.common.SocketFamily.openServerSocket(SocketFamily.java:49)
		at org.mvndaemon.mvnd.sync.IpcClient.createClient(IpcClient.java:125)
		... 33 common frames omitted
	Suppressed: java.lang.RuntimeException: Unable to create and connect to lock server
		at org.mvndaemon.mvnd.sync.IpcClient.createClient(IpcClient.java:238)
		at org.mvndaemon.mvnd.sync.IpcClient.ensureInitialized(IpcClient.java:89)
		at org.mvndaemon.mvnd.sync.IpcClient.send(IpcClient.java:290)
		at org.mvndaemon.mvnd.sync.IpcClient.newContext(IpcClient.java:342)
		... 30 common frames omitted
	Caused by: java.lang.UnsupportedOperationException: Unix sockets are supported only on JDK >= 16
		at org.mvndaemon.mvnd.common.SocketHelper.openUnixServerSocket(SocketHelper.java:30)
		at org.mvndaemon.mvnd.common.SocketFamily.openServerSocket(SocketFamily.java:49)
		at org.mvndaemon.mvnd.sync.IpcClient.createClient(IpcClient.java:125)
		... 33 common frames omitted
````

Does it ring a bell before I investigate - running on zulu 16?

**Comment by gnodet** [comment] 2021-09-02 09:37
@rmannibucau with the native or java client ?
In both case, this should not happen... Can you give the value of the `java.specification.version` system property of your JVM ?

**Comment by rmannibucau** [comment] 2021-09-02 10:21
@gnodet only tested native flavor.

Run jvm:

```
$ java -version
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment Zulu16.28+11-CA (build 16+36)
OpenJDK 64-Bit Server VM Zulu16.28+11-CA (build 16+36, mixed mode, sharing)
```

Build JVM:

```
$ java -version
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment Zulu11.45+27-CA (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.45+27-CA (build 11.0.10+9-LTS, mixed mode)
```

**Comment by gnodet** [comment] 2021-09-02 11:54
@rmannibucau you do need to build on GraalVM JDK 16

**Comment by rmannibucau** [comment] 2021-09-02 13:01
I confirm it runs well this way, thanks a lot!
On the report issue I get:

> Unexpected message type 24: ExecutionFailure{projectId='eba', halted=true, exception='org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal

Checked the daemon was using the snapshot:

> MavenDaemon --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/sun.nio.fs=ALL-UNNAMED -javaagent:/home/rmannibucau/.sdkman/candidates/mvnd/0.5.3-SNAPSHOT/mvn/lib/ext/mvnd-agent-0.5.3-SNAPSHOT.jar -Xms128M -Xmx2G -Dmvnd.home=/home/rmannibucau/.sdkman/candidates/mvnd/0.5.3-SNAPSHOT -Dmvnd.java.home=/home/rmannibucau/.sdkman/candidates/java/16.0.0-zulu -Dlogback.configurationFile=/home/rmannibucau/.sdkman/candidates/mvnd/0.5.3-SNAPSHOT/conf/logback.xml -Dmvnd.id=1eb776e4 -Dmvnd.daemonStorage=/home/rmannibucau/.m2/mvnd/registry/0.5.3-SNAPSHOT -Dmvnd.registry=/home/rmannibucau/.m2/mvnd/registry/0.5.3-SNAPSHOT/registry.bin -Dmvnd.socketFamily=inet -Djdk.java.options= --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/sun.nio.fs=ALL-UNNAMED -Dmvnd.noDaemon=false -Dmvnd.debug=false -Dmvnd.idleTimeout=3h -Dmvnd.keepAlive=100ms -Dmv

```
$ mvnd --version
mvnd native client 0.5.3-SNAPSHOT-linux-amd64 (a13f90b7fa7ea7a887101eb5b3521560f94c89ba)
Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.linux.LinuxNativePty
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: /home/rmannibucau/.sdkman/candidates/mvnd/0.5.3-SNAPSHOT/mvn
Java version: 16, vendor: Azul Systems, Inc., runtime: /home/rmannibucau/.sdkman/candidates/java/16.0.0-zulu
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "5.11.0-31-generic", arch: "amd64", family: "unix"
```

Anything wrong?
